FROM httpd

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --yes wget

RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
    && sh -c 'echo "deb https://packages.sury.org/php/ buster main" > /etc/apt/sources.list.d/php.list' \
    && apt-get update

#RUN apt-get update \
RUN apt-get install --yes php \
  && apt-get install --yes php7.3-mysql
  
WORKDIR /usr/local/apache2/htdocs
COPY . .

EXPOSE 80
