version: '3.1'

services:
  pyapp:
    image: myapp:latest
    build: .
    ports:
      - '8000:80'
    networks:
      - net1
    deploy:
      replicas: 2
    depends_on:
      - db
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /root/data-dir:/var/lib/mysql
    networks:
      - net1

networks:
  net1:
    driver: overlay
